version: 2
jobs:
  build_plugin:
    docker:
    - image: circleci/node:10
    working_directory: ~/plugin
    steps:
    - checkout
    - restore_cache:
        keys:
        - yarn-packages-{{ checksum "yarn.lock" }}
    - run:
        name: Install yarn
        command: |
          sudo npm install -g yarn --quiet
          yarn install --pure-lockfile
    - run:
        name: Run Toolkit Build
        command: npx grafana-toolkit plugin:ci-build
    - save_cache:
        paths:
        - node_modules
        key: yarn-packages-{{ checksum "yarn.lock" }}
    - persist_to_workspace:
        root: .
        paths:
        - ci
workflows:
  version: 2
  plugin_workflow:
    jobs:
    - build_plugin